### ISSUE TITLE
Compression?

### ISSUE THREAD

**Issue by kentcdodds** [timarney/react-setup#2]
You may also consider using [`compression-webpack-plugin`](https://github.com/webpack/compression-webpack-plugin) to gzip your stuff :+1:

**Comment by kentcdodds** [comment]
I personally recommend you use the `zopfli` algorithm as it compresses better (even though it's a lot slower, you only do this when deploying to production so it's worth it).

**Comment by timarney** [comment]
For sure - I found this site as a nice reference http://minime.stephan-brumme.com/react/0.14.8 .  I'm sure HTTP2 would be worth a look as well.  

Looking for pre server optimization (for this Repo).  Always love to learn new techniques.

Thanks for tweeting this https://twitter.com/kentcdodds/status/715555197188120576 .

**Comment by kentcdodds** [comment]
Wow, very cool resource! Thanks for sharing!
