### ISSUE TITLE
Add babel-plugin-remove-prop-types

### ISSUE THREAD

**Issue by kentcdodds** [timarney/react-setup#3]
You probably won't notice a difference in this project, but in real projects this can be significant: https://www.npmjs.com/package/babel-plugin-remove-prop-types

**Comment by timarney** [comment]
Cool thanks for sharing.  I'll look into that for other projects.

I heard using the es2015 preset isn't ideal for production either is that correct?  I.e. generators etc... likely are not in use for most sites.  I don't many examples of these sort of tweaks online.
``
{
  "presets": [
    "es2015",
    "react"
  ]
}

```
```

**Comment by kentcdodds** [comment]
It's probably fine. That's more of a build time performance concern. Shouldn't impact the output if you really need ES5.1 output. If you can ship to modern browsers them es2015 preset is probably overkill
