### ISSUE TITLE
Changes with Webpack 2?

### ISSUE THREAD

**Issue by kentcdodds** [timarney/react-setup#4]
I'm testing things out with webpack 2 and it looks like regardless of whether you include the `DefinePlugin` webpack is removing the `process.env.NODE_ENV` code.

I haven't had time to look too deep into it, but I thought I'd give you the heads up in case you're interested in taking a look.

**Comment by timarney** [comment]
Interesting, I'm going to update this repo next week to use the latest React etc... I'll take a look at that as well :)

**Comment by timarney** [comment]
Had some downtime today so playtime ;) see: https://github.com/timarney/react-setup/tree/wepack

Looks like in my case the **-p** from the build script actually gets picked up now.  Which is cool, so I was able to kill that part from the WebPack config.

I also found https://gist.github.com/sokra/27b24881210b56bbaff7#configuration

```
...
The function is called by the CLI and the value passed via --env is passed to the configuration function.
```
